Console.ForegroundColor = ConsoleColor.Green;
Console.WriteLine("CONTAGEM ATÉ DEZ:");
Thread.Sleep(1000);
Console.ForegroundColor = ConsoleColor.Yellow;
Console.Write("0 ");
Thread.Sleep(1000);
Console.ForegroundColor = ConsoleColor.Blue;
Console.Write("1 ");
Thread.Sleep(1000);
Console.ForegroundColor = ConsoleColor.Magenta;
Console.Write("2 ");
Thread.Sleep(1000);
Console.ForegroundColor = ConsoleColor.Green;
Console.Write("3 ");
Thread.Sleep(1000);
Console.ForegroundColor = ConsoleColor.Yellow;
Console.Write("4 ");
Thread.Sleep(1000);
Console.ForegroundColor = ConsoleColor.Blue;
Console.Write("5 ");
Thread.Sleep(1000);
Console.ForegroundColor = ConsoleColor.Magenta;
Console.Write("6 ");
Thread.Sleep(1000);
Console.ForegroundColor = ConsoleColor.Green;
Console.Write("7 ");
Thread.Sleep(1000);
Console.ForegroundColor = ConsoleColor.Yellow;
Console.Write("8 ");
Thread.Sleep(1000);
Console.ForegroundColor = ConsoleColor.Blue;
Console.Write("9 ");
Thread.Sleep(1000);
Console.ForegroundColor = ConsoleColor.Magenta;
Console.Write("10");
Console.ResetColor();
